name: CI

on:
  push:
    branches:
    - nuget-release
  pull_request:
    branches:
    - nuget-release
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'TinyTypeContainer.sln'

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore dependencies
      run: dotnet nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal