name: CI

on:
  create:
    branches:
      - release/*
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "TinyTypeContainer.sln"
      PROJECT: "TinyTypeContainer.csproj"

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v2

      - name: Get Build Version
        run: |
          Import-Module .\.build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            2.0.x
            2.1.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore $SOLUTION

      - name: Build project
        run: dotnet build $PROJECT --configuration Release

      - name: Build solution
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Run tests
        run: dotnet test --no-restore --no-build --verbosity normal

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
